///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace My1stGitHubSolution.Modules.RecordedModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseWord recording.
    /// </summary>
    [TestModule("c0e42704-15fd-4437-b133-fbc10f5bbd40", ModuleType.Recording, 1)]
    public partial class CloseWord : ITestModule
    {
        /// <summary>
        /// Holds an instance of the My1stGitHubSolution.My1stGitHubSolutionRepository repository.
        /// </summary>
        public static My1stGitHubSolution.My1stGitHubSolutionRepository repo = My1stGitHubSolution.My1stGitHubSolutionRepository.Instance;

        static CloseWord instance = new CloseWord();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseWord()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseWord Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Document1Word.Close' at Center.", repo.Document1Word.CloseInfo, new RecordItemIndex(0));
            repo.Document1Word.Close.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftWord.DontSave' at Center.", repo.MicrosoftWord.DontSaveInfo, new RecordItemIndex(1));
            repo.MicrosoftWord.DontSave.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
