///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace My1stGitHubSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the My1stGitHubSolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("0a49c7e7-e06f-4e86-9618-8fe3b79af429")]
    public partial class My1stGitHubSolutionRepository : RepoGenBaseFolder
    {
        static My1stGitHubSolutionRepository instance = new My1stGitHubSolutionRepository();
        My1stGitHubSolutionRepositoryFolders.ExplorerAppFolder _explorer;
        My1stGitHubSolutionRepositoryFolders.WordAppFolder _word;
        My1stGitHubSolutionRepositoryFolders.Document1WordAppFolder _document1word;
        My1stGitHubSolutionRepositoryFolders.MicrosoftWordAppFolder _microsoftword;

        /// <summary>
        /// Gets the singleton class instance representing the My1stGitHubSolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("0a49c7e7-e06f-4e86-9618-8fe3b79af429")]
        public static My1stGitHubSolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public My1stGitHubSolutionRepository() 
            : base("My1stGitHubSolutionRepository", "/", null, 0, false, "0a49c7e7-e06f-4e86-9618-8fe3b79af429", ".\\RepositoryImages\\My1stGitHubSolutionRepository0a49c7e7.rximgres")
        {
            _explorer = new My1stGitHubSolutionRepositoryFolders.ExplorerAppFolder(this);
            _word = new My1stGitHubSolutionRepositoryFolders.WordAppFolder(this);
            _document1word = new My1stGitHubSolutionRepositoryFolders.Document1WordAppFolder(this);
            _microsoftword = new My1stGitHubSolutionRepositoryFolders.MicrosoftWordAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0a49c7e7-e06f-4e86-9618-8fe3b79af429")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("69992444-bd31-49dc-b64c-1729f3fdfb4c")]
        public virtual My1stGitHubSolutionRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Word folder.
        /// </summary>
        [RepositoryFolder("7633481a-6e3b-4644-b94c-2b56a6e78628")]
        public virtual My1stGitHubSolutionRepositoryFolders.WordAppFolder Word
        {
            get { return _word; }
        }

        /// <summary>
        /// The Document1Word folder.
        /// </summary>
        [RepositoryFolder("dd24f890-28d0-4e11-b2ba-59204d9239fe")]
        public virtual My1stGitHubSolutionRepositoryFolders.Document1WordAppFolder Document1Word
        {
            get { return _document1word; }
        }

        /// <summary>
        /// The MicrosoftWord folder.
        /// </summary>
        [RepositoryFolder("d645c587-56c2-435f-95e1-d46d2e260d57")]
        public virtual My1stGitHubSolutionRepositoryFolders.MicrosoftWordAppFolder MicrosoftWord
        {
            get { return _microsoftword; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class My1stGitHubSolutionRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("69992444-bd31-49dc-b64c-1729f3fdfb4c")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _word2016Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, false, "69992444-bd31-49dc-b64c-1729f3fdfb4c", "")
            {
                _word2016Info = new RepoItemInfo(this, "Word2016", "?/?/container[@caption='Running applications']/?/?/toolbar[@accessiblename='Running applications']/button[@accessiblename='Word 2016']", 30000, null, "bd2c7ccc-7804-4e80-84bb-efd61ac82845");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("69992444-bd31-49dc-b64c-1729f3fdfb4c")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("69992444-bd31-49dc-b64c-1729f3fdfb4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Word2016 item.
            /// </summary>
            [RepositoryItem("bd2c7ccc-7804-4e80-84bb-efd61ac82845")]
            public virtual Ranorex.Button Word2016
            {
                get
                {
                    return _word2016Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Word2016 item info.
            /// </summary>
            [RepositoryItemInfo("bd2c7ccc-7804-4e80-84bb-efd61ac82845")]
            public virtual RepoItemInfo Word2016Info
            {
                get
                {
                    return _word2016Info;
                }
            }
        }

        /// <summary>
        /// The WordAppFolder folder.
        /// </summary>
        [RepositoryFolder("7633481a-6e3b-4644-b94c-2b56a6e78628")]
        public partial class WordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aiostartdocumentInfo;

            /// <summary>
            /// Creates a new Word  folder.
            /// </summary>
            public WordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Word", "/form[@title='Word']", parentFolder, 30000, null, false, "7633481a-6e3b-4644-b94c-2b56a6e78628", "")
            {
                _aiostartdocumentInfo = new RepoItemInfo(this, "AIOStartDocument", ".//container[@automationid='BackstageView']/?/?/container[@name='New']/container[@name='Featured']/link[@name='Blank document']", 30000, null, "9ab4a776-14b5-4262-adc1-4923e21a20cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7633481a-6e3b-4644-b94c-2b56a6e78628")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7633481a-6e3b-4644-b94c-2b56a6e78628")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AIOStartDocument item.
            /// </summary>
            [RepositoryItem("9ab4a776-14b5-4262-adc1-4923e21a20cc")]
            public virtual Ranorex.Link AIOStartDocument
            {
                get
                {
                    return _aiostartdocumentInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The AIOStartDocument item info.
            /// </summary>
            [RepositoryItemInfo("9ab4a776-14b5-4262-adc1-4923e21a20cc")]
            public virtual RepoItemInfo AIOStartDocumentInfo
            {
                get
                {
                    return _aiostartdocumentInfo;
                }
            }
        }

        /// <summary>
        /// The Document1WordAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd24f890-28d0-4e11-b2ba-59204d9239fe")]
        public partial class Document1WordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Document1Word  folder.
            /// </summary>
            public Document1WordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Document1Word", "/form[@title='Document1 - Word']", parentFolder, 30000, null, false, "dd24f890-28d0-4e11-b2ba-59204d9239fe", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "container[@caption='MsoDockTop']/container[@caption='Ribbon']//container[@name='Ribbon']/button[@name='Close']", 30000, null, "273e81cc-4cbc-4033-9087-c24e8c5211e8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd24f890-28d0-4e11-b2ba-59204d9239fe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd24f890-28d0-4e11-b2ba-59204d9239fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("273e81cc-4cbc-4033-9087-c24e8c5211e8")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("273e81cc-4cbc-4033-9087-c24e8c5211e8")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The MicrosoftWordAppFolder folder.
        /// </summary>
        [RepositoryFolder("d645c587-56c2-435f-95e1-d46d2e260d57")]
        public partial class MicrosoftWordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dontsaveInfo;

            /// <summary>
            /// Creates a new MicrosoftWord  folder.
            /// </summary>
            public MicrosoftWordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftWord", "/form[@title='Microsoft Word']", parentFolder, 30000, null, false, "d645c587-56c2-435f-95e1-d46d2e260d57", "")
            {
                _dontsaveInfo = new RepoItemInfo(this, "DontSave", "?/?/element[@name='Microsoft Word']/button[@name='Don''t Save']", 30000, null, "d02dee3d-a7d6-488f-81dd-72acb9de8870");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d645c587-56c2-435f-95e1-d46d2e260d57")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d645c587-56c2-435f-95e1-d46d2e260d57")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DontSave item.
            /// </summary>
            [RepositoryItem("d02dee3d-a7d6-488f-81dd-72acb9de8870")]
            public virtual Ranorex.Button DontSave
            {
                get
                {
                    return _dontsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DontSave item info.
            /// </summary>
            [RepositoryItemInfo("d02dee3d-a7d6-488f-81dd-72acb9de8870")]
            public virtual RepoItemInfo DontSaveInfo
            {
                get
                {
                    return _dontsaveInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}