///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HelloWorld
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HelloWorldRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("2c4d33be-2700-4204-9d76-7889d623810c")]
    public partial class HelloWorldRepository : RepoGenBaseFolder
    {
        static HelloWorldRepository instance = new HelloWorldRepository();

        /// <summary>
        /// Gets the singleton class instance representing the HelloWorldRepository element repository.
        /// </summary>
        [RepositoryFolder("2c4d33be-2700-4204-9d76-7889d623810c")]
        public static HelloWorldRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HelloWorldRepository() 
            : base("HelloWorldRepository", "/", null, 0, false, "2c4d33be-2700-4204-9d76-7889d623810c", ".\\RepositoryImages\\HelloWorldRepository2c4d33be.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2c4d33be-2700-4204-9d76-7889d623810c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class HelloWorldRepositoryFolders
    {
    }
#pragma warning restore 0436
}